Repository pnp/powershell, pull requests merged in 2023-03, with the labels that each got.

#2884 Adding support for `Set-PnPSearchSettings` to be used with vanity domain tenants
  CHANGELOG.md
  src/Commands/Apps/GrantAzureADAppSitePermission.cs
  src/Commands/Search/SetSearchSettings.cs
Labels: pending PnP Framework merge

#2887 Fix #2831: issue with creating teamsites in non-commercial cloud environments
  CHANGELOG.md
  src/Commands/Admin/NewSite.cs
Labels: pending PnP Framework merge

#2881 Feature #2863: Added support for setting the Azure AD app logo if specified
  CHANGELOG.md
  documentation/Register-PnPAzureADApp.md
  src/Commands/AzureAD/RegisterAzureADApp.cs
Labels: in review

#2869 Support document library owner to make change of the file version trim mode
  CHANGELOG.md
  documentation/Set-PnPList.md
  src/Commands/Lists/SetList.cs
Labels: in review, pending CSOM release
